
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package CUP;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int XOR = 17;
  public static final int RESTA = 5;
  public static final int INT = 32;
  public static final int PUNTOCOMA = 24;
  public static final int NOEQUIVALENTE = 14;
  public static final int IDENTIFICADOR = 2;
  public static final int NOT = 18;
  public static final int MENORIGUAL = 10;
  public static final int AND = 15;
  public static final int LLLAVE = 21;
  public static final int OR = 16;
  public static final int LPARENTESIS = 19;
  public static final int BOOL = 33;
  public static final int RLLAVE = 22;
  public static final int SUMA = 4;
  public static final int MAIN = 31;
  public static final int IF = 26;
  public static final int MAYORIGUAL = 11;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int FUNT = 35;
  public static final int MODULO = 8;
  public static final int MENOR = 13;
  public static final int valor = 3;
  public static final int ASIGNACION = 23;
  public static final int MAYOR = 12;
  public static final int ELSE = 27;
  public static final int WHILE = 28;
  public static final int PROC = 34;
  public static final int DIVISION = 7;
  public static final int EQUIVALENTE = 9;
  public static final int DO = 29;
  public static final int RPARENTESIS = 20;
  public static final int MULTIPLICACION = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "valor",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "EQUIVALENTE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "MAYOR",
  "MENOR",
  "NOEQUIVALENTE",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "LPARENTESIS",
  "RPARENTESIS",
  "LLLAVE",
  "RLLAVE",
  "ASIGNACION",
  "PUNTOCOMA",
  "COMA",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "RETURN",
  "MAIN",
  "INT",
  "BOOL",
  "PROC",
  "FUNT"
  };
}

